UPSTREAM: util/u_printf: Fix const correctness in util_printf_next_spec_pos
Fix compiler error:

../src/util/u_printf.c:75:13: error: initializing 'char *' with an
expression of type 'const char *' discards qualifiers
[-Werror,-Wincompatible-pointer-types-discards-qualifiers]
   75 |       char *spec_pos = strpbrk(str_found, "cdieEfFgGaAosuxXp%");
      |             ^          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

glibc now provides C23-style type-generic string functions. strpbrk
returns const char * when passed a const char * argument. Update
spec_pos declaration to match.

Fixes: 6d263ff5a3ec ("util: Convert util/u_printf.cpp to util/u_printf.c")
Reviewed-by: Yonggang Luo <luoyonggang@gmail.com>
(cherry picked from commit c576d64801de0352cfd9b9e0067758f2283f95dd)

Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/39117>

Backport Notes:
- resolve trivial .pick_status.json conflict

BUG=b:491765858
TEST=Local build on eve with glibc 2.43; CQ.

Change-Id: Ic62a638291204861b2bd0679a6f5bf21dbdd7e5b
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/mesa/+/7849839
Commit-Queue: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>
Reviewed-by: George Burgess <gbiv@chromium.org>
Reviewed-by: Yiwei Zhang <zzyiwei@google.com>
Auto-Submit: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>
Reviewed-by: Sean Paul <sean@poorly.run>
Tested-by: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>