UPSTREAM: util/u_printf: Fix const correctness in util_printf_next_spec_pos
Fix compiler error:

../src/util/u_printf.c:75:13: error: initializing 'char *' with an
expression of type 'const char *' discards qualifiers
[-Werror,-Wincompatible-pointer-types-discards-qualifiers]
   75 |       char *spec_pos = strpbrk(str_found, "cdieEfFgGaAosuxXp%");
      |             ^          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

glibc now provides C23-style type-generic string functions. strpbrk
returns const char * when passed a const char * argument. Update
spec_pos declaration to match.

Fixes: 6d263ff5a3ec ("util: Convert util/u_printf.cpp to util/u_printf.c")
Signed-off-by: Vinson Lee <vlee@freedesktop.org>
Reviewed-by: Yonggang Luo <luoyonggang@gmail.com>
(cherry picked from commit c576d64801de0352cfd9b9e0067758f2283f95dd)
Link: https://gitlab.freedesktop.org/mesa/mesa/-/commit/c576d64801de0352cfd9b9e0067758f2283f95dd

Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/39117>

BUG=b:491765858
TEST=emerge-grunt media-libs/mesa-amd compiles cleanly

Change-Id: I54ed04be9ec2ac19ffd281fdab62920ae43f03d6
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/mesa/+/7993239
Commit-Queue: Denys Fedoryshchenko <denys.f@collabora.corp-partner.google.com>
Tested-by: Denys Fedoryshchenko <denys.f@collabora.corp-partner.google.com>
Reviewed-by: Chia-I Wu <olv@google.com>
Auto-Submit: Denys Fedoryshchenko <denys.f@collabora.corp-partner.google.com>
Reviewed-by: George Burgess <gbiv@chromium.org>